### ISSUE TITLE
`None` being prepended to relative path for downloaded images

### ISSUE THREAD

**Issue by markstickley** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#39]
Plugin version: 0.6.1

mkdocs.yaml:
```
site_name: 'my-site'

nav:
  - Home: index.md
  - Development: development.md

plugins:
  - techdocs-core
  - kroki:
      DownloadImages: true
      DownloadDir: "images/kroki_generated"
```

Generated image tag:
```
<img alt="Kroki" src="Noneimages/kroki_generated/krokitest-577414e8fb4a6f6ddb993d1827fd6937.svg" />
```

Note that without the `DownloadDir` config option, the `src` is just `Nonekrokitest-577414e8fb4a6f6ddb993d1827fd6937.svg`

The svg is being generated and saved just fine, it's the html img tag that has the problem.
