### ISSUE TITLE
Trigger kroki *only* for PDF build

### ISSUE THREAD

**Issue by m5c** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#77]
I have kroki enabled in my mkdocs like this:

```
plugins:
  - search
  - mermaid2
  - with-pdf
  - kroki:
      FencePrefix: ''
      FileTypeOverrides:
        mermaid: png
```

This works just fine for generating the PDF. However I still need to build a classic webpage in parallel, and I do not want kroki to replace the pretty-rendered svg mermaids in the web version.

Is there a parameter to limit kroki to the PDF build ?
