### ISSUE TITLE
Image height miscalculation while rendering in SVG format

### ISSUE THREAD

**Issue by btek-fng** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#79]
When activating the SVG inline rendering (which replaces the default `<img>` tag with `<svg>`), a top margin appears on the embedded image.

* plugin configuration :
```
plugins:
  - kroki:
      ServerURL: !ENV [KROKI_SERVER_URL, 'https://kroki.io']
      FileTypes:
        - svg
      TagFormat: svg
```

* puml file used :

[Github - C4_Container Diagram Sample - bigbankplc.puml](https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/samples/C4_Container%20Diagram%20Sample%20-%20bigbankplc.puml)

* result :

![kroki_margin](https://github.com/user-attachments/assets/2873628a-d751-4239-9070-8c4880d48709)

It seems like manually removing the `height` attributes within the html, makes rendering correct.
